# Generated by Django 3.2.5 on 2022-01-07 08:23

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(db_column='Variant_name', max_length=150)),
                ('reference_genome', models.TextField(blank=True, db_column='Reference_genome', null=True)),
                ('transcript_id', models.TextField(blank=True, db_column='Transcript_ID', null=True)),
                ('chromosome', models.TextField(blank=True, db_column='Chromosome', null=True)),
                ('genomic_start_position', models.TextField(blank=True, db_column='Genomic_start_position', null=True)),
                ('genomic_end_position', models.TextField(blank=True, db_column='Genomic_end_position', null=True)),
                ('reference_allele', models.TextField(blank=True, db_column='Reference_allele', null=True)),
                ('alternate_allele', models.TextField(blank=True, db_column='Alternate_allele', null=True)),
                ('disease_association_with_ref_allele', models.TextField(blank=True, db_column='Disease_association_with_ref_allele', null=True)),
                ('variant_type', models.TextField(blank=True, db_column='Variant_type', null=True)),
            ],
            options={
                'db_table': 'variant_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VariantDetailsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
