# Generated by Django 3.2.11 on 2022-01-19 11:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('gene_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantDetailsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='VariantDetails',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('variant_name', models.CharField(max_length=150)),
                ('reference_genome', models.TextField(blank=True, null=True)),
                ('transcript_id', models.TextField(blank=True, null=True)),
                ('chromosome', models.TextField(blank=True, null=True)),
                ('genomic_start_position', models.TextField(blank=True, null=True)),
                ('genomic_end_position', models.TextField(blank=True, null=True)),
                ('reference_allele', models.TextField(blank=True, null=True)),
                ('alternate_allele', models.TextField(blank=True, null=True)),
                ('disease_association_with_ref_allele', models.TextField(blank=True, null=True)),
                ('variant_type', models.TextField(blank=True, null=True)),
                ('gene', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_details', to='gene_details.genedetails')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MtVep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_ncbi_geneid', models.TextField(blank=True, null=True)),
                ('query_prediction', models.TextField(blank=True, null=True)),
                ('query_model', models.TextField(blank=True, null=True)),
                ('variant', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mt_vep', to='variant_details.variantdetails')),
            ],
        ),
        migrations.CreateModel(
            name='EnsemblVep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensembl_canonical_hgvsc', models.TextField(blank=True, null=True)),
                ('consequence_terms', models.TextField(blank=True, null=True)),
                ('af_1000gp3_eur', models.IntegerField(blank=True, null=True)),
                ('af_1000gp3', models.IntegerField(blank=True, null=True)),
                ('af_1000gp3_afr', models.IntegerField(blank=True, null=True)),
                ('af_1000gp3_amr', models.IntegerField(blank=True, null=True)),
                ('af_1000gp3_sas', models.IntegerField(blank=True, null=True)),
                ('af_1000gp3_eas', models.IntegerField(blank=True, null=True)),
                ('exac_adj_af', models.IntegerField(blank=True, null=True)),
                ('exac_afr_af', models.IntegerField(blank=True, null=True)),
                ('exac_amr_af', models.IntegerField(blank=True, null=True)),
                ('exac_eas_af', models.IntegerField(blank=True, null=True)),
                ('exac_nfe_af', models.IntegerField(blank=True, null=True)),
                ('exac_sas_af', models.IntegerField(blank=True, null=True)),
                ('gnomad_genomes_af', models.IntegerField(blank=True, null=True)),
                ('gnomad_genomes_afr_af', models.IntegerField(blank=True, null=True)),
                ('gnomad_genomes_eas_af', models.IntegerField(blank=True, null=True)),
                ('study_acmg', models.TextField(blank=True, null=True)),
                ('polyphen2_hvar_score', models.TextField(blank=True, null=True)),
                ('polyphen2_hvar_pred', models.TextField(blank=True, null=True)),
                ('sift4g_score', models.TextField(blank=True, null=True)),
                ('sift4g_pred', models.TextField(blank=True, null=True)),
                ('fathmm_score', models.TextField(blank=True, null=True)),
                ('fathmm_pred', models.TextField(blank=True, null=True)),
                ('sift_score', models.IntegerField(blank=True, null=True)),
                ('sift_prediction', models.TextField(blank=True, null=True)),
                ('cadd_raw', models.IntegerField(blank=True, null=True)),
                ('cadd_phred', models.IntegerField(blank=True, null=True)),
                ('variant', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ensembl_vep', to='variant_details.variantdetails')),
            ],
        ),
    ]
