# Generated by Django 3.2.11 on 2022-01-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantdetails',
            name='disease_association_with_ref_allele',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
