# Generated by Django 3.2.11 on 2022-01-14 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.TextField(blank=True, null=True)),
                ('reported_allele_or_genotype', models.TextField(blank=True, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('condition_description', models.TextField(blank=True, null=True)),
                ('disease_status', models.TextField(blank=True, null=True)),
                ('odds_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('p_value', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_variants', to='studies.studies')),
            ],
        ),
    ]
