# Generated by Django 3.2.11 on 2022-01-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study_variants', '0001_initial'),
        ('variant_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyvariants',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variant_details.variantdetails'),
        ),
    ]
