# Generated by Django 3.2.11 on 2022-01-19 11:52

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study_variants', '0001_initial'),
        ('variant_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyvariants',
            name='variant',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variant_details.variantdetails'),
        ),
    ]
