# Generated by Django 3.2.11 on 2022-01-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_variants', '0002_studyvariants_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyvariants',
            name='odds_ratio',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='studyvariants',
            name='p_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
