# Generated by Django 3.2.11 on 2022-01-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_variants', '0003_auto_20220121_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyvariants',
            name='odds_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyvariants',
            name='p_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
