# Generated by Django 3.2.11 on 2022-03-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_variants', '0007_alter_studyvariants_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyvariants',
            name='p_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
    ]
