# Generated by Django 3.2.11 on 2022-03-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studies',
            options={'verbose_name': 'Study', 'verbose_name_plural': 'Studies'},
        ),
    ]
