# Generated by Django 4.0.4 on 2022-10-07 13:00

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_alter_studies_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiesindexpage',
            name='study_findings_intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
