# Generated by Django 3.2.11 on 2022-01-19 11:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneDetails',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('gene', models.CharField(max_length=150)),
                ('cytoband_position', models.TextField(blank=True, null=True)),
                ('omim', models.IntegerField(blank=True, null=True)),
                ('rvis_score', models.IntegerField(blank=True, null=True)),
                ('rvis_percentage', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GeneDetailsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='GeneHpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('hpoid', models.TextField(blank=True, null=True)),
                ('alternativeid', models.TextField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('inputterm', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gene_hpo', to='gene_details.genedetails')),
            ],
        ),
    ]
