# Generated by Django 3.2.11 on 2022-01-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gene_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genedetails',
            options={'managed': False},
        ),
    ]
