# Generated by Django 3.2.11 on 2022-01-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene_details', '0002_auto_20220121_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genedetails',
            name='rvis_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genedetails',
            name='rvis_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
