# Generated by Django 3.2.11 on 2022-01-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene_details', '0003_auto_20220121_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genedetails',
            name='rvis_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='genedetails',
            name='rvis_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
