# Generated by Django 3.2.11 on 2022-03-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gene_details', '0004_auto_20220121_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genedetails',
            options={'verbose_name': 'Gene', 'verbose_name_plural': 'Genes'},
        ),
        migrations.AlterModelOptions(
            name='genehpo',
            options={'verbose_name': 'Gene HPO', 'verbose_name_plural': 'Gene HPO'},
        ),
    ]
